module: Credentials
author: IBM
github_url: https://github.com/KituraKommunity/Kitura-Credentials/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Kitura-Credentials.xcodeproj, -target, Credentials, LIBRARY_SEARCH_PATHS=.build/debug]

